import * as fs from 'node:fs';

import { getFs } from './registry';

export const accessSync = (...args: any[]) => getFs().accessSync(...args);
export const appendFileSync = (...args: any[]) => getFs().appendFileSync(...args);
export const chmodSync = (...args: any[]) => getFs().chmodSync(...args);
export const chownSync = (...args: any[]) => getFs().chownSync(...args);
export const closeSync = (...args: any[]) => getFs().closeSync(...args);
export const copyFileSync = (...args: any[]) => getFs().copyFileSync(...args);
export const cpSync = (...args: any[]) => getFs().cpSync(...args);
export const existsSync = (...args: any[]) => getFs().existsSync(...args);
export const fchmodSync = (...args: any[]) => getFs().fchmodSync(...args);
export const fchownSync = (...args: any[]) => getFs().fchownSync(...args);
export const fdatasyncSync = (...args: any[]) => getFs().fdatasyncSync(...args);
export const fstatSync = (...args: any[]) => getFs().fstatSync(...args);
export const fsyncSync = (...args: any[]) => getFs().fsyncSync(...args);
export const ftruncateSync = (...args: any[]) => getFs().ftruncateSync(...args);
export const futimesSync = (...args: any[]) => getFs().futimesSync(...args);
export const lchmodSync = (...args: any[]) => getFs().lchmodSync(...args);
export const lchownSync = (...args: any[]) => getFs().lchownSync(...args);
export const linkSync = (...args: any[]) => getFs().linkSync(...args);
export const lstatSync = (...args: any[]) => getFs().lstatSync(...args);
export const lutimesSync = (...args: any[]) => getFs().lutimesSync(...args);
export const mkdirSync = (...args: any[]) => getFs().mkdirSync(...args);
export const mkdtempSync = (...args: any[]) => getFs().mkdtempSync(...args);
export const openSync = (...args: any[]) => getFs().openSync(...args);
export const opendirSync = (...args: any[]) => getFs().opendirSync(...args);
export const readFileSync = (...args: any[]) => getFs().readFileSync(...args);
export const readdirSync = (...args: any[]) => getFs().readdirSync(...args);
export const readlinkSync = (...args: any[]) => getFs().readlinkSync(...args);
export const readSync = (...args: any[]) => getFs().readSync(...args);
export const readvSync = (...args: any[]) => getFs().readvSync(...args);
export const realpathSync = (...args: any[]) => getFs().realpathSync(...args);
export const renameSync = (...args: any[]) => getFs().renameSync(...args);
export const rmSync = (...args: any[]) => getFs().rmSync(...args);
export const rmdirSync = (...args: any[]) => getFs().rmdirSync(...args);
export const statSync = (...args: any[]) => getFs().statSync(...args);
export const statfsSync = (...args: any[]) => getFs().statfsSync(...args);
export const symlinkSync = (...args: any[]) => getFs().symlinkSync(...args);
export const truncateSync = (...args: any[]) => getFs().truncateSync(...args);
export const unlinkSync = (...args: any[]) => getFs().unlinkSync(...args);
export const utimesSync = (...args: any[]) => getFs().utimesSync(...args);
export const writeFileSync = (...args: any[]) => getFs().writeFileSync(...args);
export const writeSync = (...args: any[]) => getFs().writeSync(...args);
export const writevSync = (...args: any[]) => getFs().writevSync(...args);

export const Dirent = fs.Dirent;
export const Dir = fs.Dir;
export const Stats = fs.Stats;
export const constants = fs.constants;
