// names stay in source declaration order, not sorted -- the built union types this barrel
// re-exports render in export-list order, and a sorted list changes that rendering
// eslint-disable-next-line simple-import-sort/exports -- see comment above
export {
  NOT_IMPLEMENTED_ERROR_BRAND,
  PROCESS_EXIT_ERROR_BRAND,
  PROCESS_SPAWN_ERROR_BRAND,
  JSON_PARSE_ERROR_BRAND,
  type INotImplementedErrorOptions,
  NotImplementedError,
  type IProcessExitErrorOptions,
  ProcessExitError,
  type IProcessSpawnErrorOptions,
  ProcessSpawnError,
  type IJsonParseErrorOptions,
  JsonParseError,
  isNotImplementedError,
  isProcessExitError,
  isProcessSpawnError,
  isJsonParseError,
} from './errors/classes';
export {
  type NodeErrnoError,
  type ENOENT,
  type EACCES,
  type EPERM,
  type EROFS,
  type EEXIST,
  type EISDIR,
  type ENOTDIR,
  type ENOTEMPTY,
  type EBUSY,
  type EAGAIN,
  type EMFILE,
  type ENFILE,
  type ENOSPC,
  type EDQUOT,
  type EXDEV,
  type ELOOP,
  type ENAMETOOLONG,
  type EINVAL,
  type EIO,
  type EPIPE,
  type ECONNREFUSED,
  type ECONNRESET,
  type ETIMEDOUT,
  type EHOSTUNREACH,
  type ENETUNREACH,
  type EADDRINUSE,
  type EADDRNOTAVAIL,
  type EMSGSIZE,
  type ENOTFOUND,
  type ENODATA,
  type ESERVFAIL,
  type EREFUSED,
  type EBADNAME,
  type EFORMERR,
  type ECANCELLED,
  isErrno,
  isNotFoundError,
  isPermissionError,
  isExistsError,
  isIsDirError,
  isNotDirError,
  isNotEmptyError,
  isBusyError,
  isNoSpaceError,
  isTooManyFilesError,
  isCrossDeviceError,
} from './errors/errno';
export { features } from './features';
